project:
    machine_name: drub
    prefix: DRUB
    human_name: 'Drub'
    profile:
        name: lightning
        contrib: true
    local:
        protocol: http
        hostname: '${project.machine_name}.localhost'
git:
    default_branch: master
    remotes:
        - 'eenshah@svn-2411.prod.hosting.acquia.com:eenshah.git'
drush:
    aliases:
        remote: '${project.machine_name}.test'
        local: self
        ci: self
    default_alias: '${drush.aliases.local}'
target-hooks:
    frontend-setup:
        dir: '${docroot}'
        command: 'echo ''No frontend setup configured.'''
    frontend-build:
        dir: '${docroot}'
        command: 'echo ''No frontend build configured.'''
    post-deploy-build:
        dir: '${deploy.dir}/docroot/profiles/contrib/lightning'
        command: 'npm run install-libraries'
    post-setup-build:
        dir: '${docroot}/profiles/contrib/lightning'
        command: 'npm run install-libraries'
import: null
